#!/usr/bin/env bash
# Dev loop for the Linux container. Run from the host, from anywhere in the repo.
#
#   ./scripts/dev.sh up                 build image + start container (idempotent)
#   ./scripts/dev.sh build [preset]     configure + build      (default: debug)
#   ./scripts/dev.sh test  [preset] [-R regex]
#   ./scripts/dev.sh server [args...]   run tiny-redis-server (release)
#   ./scripts/dev.sh cli   [args...]    redis-cli against it
#   ./scripts/dev.sh bench [args...]    redis-benchmark against it
#   ./scripts/dev.sh hw                 capture host/toolchain facts -> docs/hardware.txt
#   ./scripts/dev.sh fmt [--fix]        clang-format, same check CI runs
#   ./scripts/dev.sh tidy [preset]      clang-tidy over the compile database
#   ./scripts/dev.sh shell              interactive shell in the container
#   ./scripts/dev.sh down | clean       stop container | stop and drop build volume
#
# Presets: debug | release | asan | tsan
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

SERVICE=dev
CONTAINER=tiny-redis-dev
PORT=6380

if docker compose version >/dev/null 2>&1; then
  DC=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  DC=(docker-compose)
else
  echo "error: docker compose not found. Install Docker Desktop and start it." >&2
  exit 1
fi

die() { echo "error: $*" >&2; exit 1; }

running() { [ "$(docker inspect -f '{{.State.Running}}' "$CONTAINER" 2>/dev/null || echo false)" = "true" ]; }

up() {
  if ! running; then
    "${DC[@]}" up -d --build "$SERVICE"
  fi
  local guest host
  guest="$(docker exec "$CONTAINER" uname -m)"
  host="$(uname -m)"
  # arm64 on the host maps to aarch64 in the guest; anything else means the image is
  # running under emulation and no timing from it is trustworthy.
  if [ "$host" = "arm64" ] && [ "$guest" != "aarch64" ]; then
    echo "WARNING: container is $guest on an arm64 host -- that is Rosetta emulation." >&2
    echo "         Correctness is fine; every benchmark number from it is garbage." >&2
    echo "         Rebuild without a linux/amd64 platform pin." >&2
  fi
}

# Runs a command in the container. Interactive when we have a tty.
dex() {
  local flags=(-i)
  [ -t 0 ] && [ -t 1 ] && flags+=(-t)
  docker exec "${flags[@]}" -w /work "$CONTAINER" "$@"
}

preset_or_default() {
  case "${1:-}" in
    debug|release|asan|tsan) echo "$1" ;;
    *) echo debug ;;
  esac
}

cmd_build() {
  local preset; preset="$(preset_or_default "${1:-}")"; shift || true
  up
  dex cmake --preset "$preset"
  dex cmake --build --preset "$preset" "$@"
}

cmd_test() {
  local preset; preset="$(preset_or_default "${1:-}")"
  case "${1:-}" in debug|release|asan|tsan) shift ;; esac
  cmd_build "$preset"
  dex ctest --preset "$preset" "$@"
}

cmd_server() {
  cmd_build release
  echo "--- tiny-redis-server (ctrl-c to stop) ---"
  echo "note: binding 0.0.0.0 so the published host port works; loopback-only inside"
  echo "      the container is what you want for benchmarking."
  dex ./build/release/tiny-redis-server --bind 0.0.0.0 --port "$PORT" "$@"
}

cmd_hw() {
  up
  local out=docs/hardware.txt
  {
    echo "# Generated by scripts/dev.sh hw -- do not edit by hand."
    echo "# Every published benchmark number must name the machine it came from."
    echo
    echo "## container"
    dex sh -c 'uname -srmo; echo; cat /etc/os-release | head -2'
    echo
    echo "## cpu"
    dex sh -c 'lscpu 2>/dev/null | grep -Ei "^(Architecture|Model name|CPU\(s\)|Thread|Core|Socket|BogoMIPS|L1d|L1i|L2|L3)" || cat /proc/cpuinfo | head -30'
    echo
    echo "## memory"
    dex sh -c 'free -h 2>/dev/null || grep MemTotal /proc/meminfo'
    echo
    echo "## toolchain"
    dex sh -c 'g++ --version | head -1; clang++ --version | head -1; cmake --version | head -1; ninja --version; redis-cli --version; redis-benchmark --version'
    echo
    echo "## docker host"
    echo "host uname: $(uname -srm)"
    docker info --format 'docker: {{.ServerVersion}}  cpus: {{.NCPU}}  mem: {{.MemTotal}}' 2>/dev/null || true
    if [ "$(uname -s)" = "Darwin" ]; then
      echo "host cpu:   $(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo unknown)"
      echo "host cores: $(sysctl -n hw.ncpu) (perf $(sysctl -n hw.perflevel0.logicalcpu 2>/dev/null || echo '?') / eff $(sysctl -n hw.perflevel1.logicalcpu 2>/dev/null || echo '?'))"
      echo "host mem:   $(( $(sysctl -n hw.memsize) / 1024 / 1024 / 1024 )) GiB"
    fi
  } > "$out"
  echo "wrote $out"
  echo
  cat "$out"
}

cmd_fmt() {
  up
  if [ "${1:-}" = "--fix" ]; then
    dex sh -c 'find src tests bench -name "*.cpp" -o -name "*.h" | xargs clang-format -i'
    echo "formatted in place"
  else
    dex sh -c 'find src tests bench -name "*.cpp" -o -name "*.h" | xargs clang-format --dry-run --Werror'
    echo "format clean"
  fi
}

cmd_tidy() {
  local preset; preset="$(preset_or_default "${1:-}")"
  cmd_build "$preset"
  dex sh -c "find src -name '*.cpp' | xargs clang-tidy -p build/$preset"
}

case "${1:-}" in
  up)      shift; up ;;
  build)   shift; cmd_build "$@" ;;
  test)    shift; cmd_test "$@" ;;
  server)  shift; cmd_server "$@" ;;
  cli)     shift; up; dex redis-cli -p "$PORT" "$@" ;;
  bench)   shift; up; dex redis-benchmark -p "$PORT" "$@" ;;
  hw)      shift; cmd_hw ;;
  fmt)     shift; cmd_fmt "$@" ;;
  tidy)    shift; cmd_tidy "$@" ;;
  shell)   shift; up; dex bash ;;
  down)    shift; "${DC[@]}" down ;;
  clean)   shift; "${DC[@]}" down -v ;;
  ""|-h|--help|help)
    # Print the header comment block, stopping at the first non-comment line.
    awk 'NR>1 { if (!/^#/) exit; sub(/^# ?/, ""); print }' "${BASH_SOURCE[0]}" ;;
  *)       die "unknown command '$1' (try: $0 help)" ;;
esac
